version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom nginx.conf
    depends_on:
      - wordpress
    networks:
      - cg

  mysql:
    image: mariadb:11.1.2-jammy
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: wordpress
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "--silent"]
      start_period: 55s
      interval: 1s
      timeout: 15s
      retries: 15
    container_name: mysql
    networks:
      - cg

  wordpress:
    image: wordpress:6.5.5
    restart: always
    volumes:
      - wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: username
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    container_name: app
    depends_on:
      - mysql
    networks:
      - cg

volumes:
  db_data:
  wp_data:

networks:
  cg:
    driver: bridge
